name: shiki_admin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  http: ^0.13.4
  dropdown_button2: 1.6.3
  provider: 6.0.3
  expandable: 5.0.1
  flutter_colorpicker: 1.0.3
  flutter_expanded_tile: ^0.3.6
  google_fonts: 3.0.1
  shared_preferences: ^2.0.15
  bloc: ^8.1.0
  keyboard_dismisser: ^3.0.0
  sentry_flutter: ^6.18.1
  flutter_bloc: ^8.1.1
  retrofit: ^3.3.1
  dio: ^4.0.6
  auto_route: ^5.0.4
  get_it: ^7.2.0
  intl: ^0.17.0
  formz: ^0.4.1
  injectable: ^2.1.0
  package_info_plus: ^3.0.2 
  json_annotation: ^4.7.0
  dartz: ^0.10.1
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  freezed: ^2.3.2
  injectable_generator: ^2.1.0
  retrofit_generator: ^4.2.0
  json_serializable: ^6.5.4

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true